name: Update db animes and mangas

on:
  schedule:
    # Once per week, because there a lot of mangas to load (more than 60,000)
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  cron:
    env:
      DATABASE_URL: '${{secrets.DATABASE_URL}}'
      DATABASE_AUTH_TOKEN: '${{secrets.DATABASE_AUTH_TOKEN}}'
      PUBLIC_MAL_CLIENT_ID: '${{secrets.PUBLIC_MAL_CLIENT_ID}}'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: false
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run seed script
        run: pnpm run seed
